import mongoose from 'mongoose';
import ledgerModel from '../models/ledger.model.js'

const accountSchema = new mongoose.Schema({
 user: {
  // here type is used to specify the data type of the field, in this case it is an objectid which is unique idetifier generated by db for each document
  type: mongoose.Schema.Types.ObjectId,
  // reference is used to establish relationship between two collections in mongodb, it is used to reference the user colelction in the account collection, it is used to store the user id in the account collection
  ref: "user",
  required: [true, "Account must be associated witha user"],
  index: true  // it is used to create an index on the user field, used to improve the performance of queries that filter by user field
 },
 status: {
  type: String,
  enum: {
   values: ["ACTIVE", "FROZEN", "CLOSED"],
   message: "Status must be either ACTIVE, FROZEN or CLOSED",
  },
  default: "ACTIVE"
 },
 currency: {
  type: String,
  required: [true, "Currency is required for creating an account"],
  default: "INR"
 },

}, {
 timestamps: true
})

// indexes created on user and status fields - COMPOUND INDEX
accountSchema.index({ user: 1, status: 1 }) // user: 1 is used to create an index on user field in ascending order. status:1 is used for status field

// this method is used to get the balance 
accountSchema.methods.getBalance = async function () {
 const balanceData = await ledgerModel.aggregate([
  { $match: { account: this._id } }, // this line is used to match the account id with the account id of the ledger collection
  {
   $group: {
    _id: null,
    totalDebit: {
     $sum: { $cond: [{ $eq: ["$type", "DEBIT"] }, "$amount", 0] }
    },
    totalCredit: {
     $sum: { $cond: [{ $eq: ["$type", "CREDIT"] }, "$amount", 0] }
    },
   },
  },
  {
   $project: {
    _id: 0,
    balance: { $subtract: ['$totalCredit', '$totalDebit'] }
   }
  }
 ])

 if(balanceData.length === 0) return 0;
 return balanceData[0].balance;
}

/* This code snippet defines a method called 
getBalance
d:\Bank-transaction-system-backend\src\models\account.model.js
 on the accountSchema object. This method is an asynchronous function that calculates the balance of an account by querying the ledgerModel collection.

Here's a breakdown of what the code does:

It uses the aggregate method of the ledgerModel collection to perform a series of operations on the data.
The $match stage filters the documents in the ledgerModel collection based on the account field matching the _id of the current account instance.
The $group stage groups the filtered documents by _id (which is set to null in this case) and calculates the sum of the amount field for documents with a type of "DEBIT" and "CREDIT" respectively.
The $project stage shapes the result of the aggregation pipeline by excluding the _id field and calculating the balance as the difference between totalCredit and totalDebit.
Overall, this code snippet allows an account instance to retrieve its balance by querying the ledgerModel collection. */

const accountModel = mongoose.model("account", accountSchema);

export default accountModel;