import mongoose from 'mongoose';

const accountSchema = new mongoose.Schema({
 user: {
  // here type is used to specify the data type of the field, in this case it is an objectid which is unique idetifier generated by db for each document
  type: mongoose.Schema.Types.ObjectId,
  // reference is used to establish relationship between two collections in mongodb, it is used to reference the user colelction in the account collection, it is used to store the user id in the account collection
  ref: "user",
  required: [true, "Account must be associated witha user"],
  index: true  // it is used to create an index on the user field, used to improve the performance of queries that filter by user field
 },
 status: {
  type: String,
  enum: {
   values: ["ACTIVE", "FROZEN", "CLOSED"],
   message: "Status must be either ACTIVE, FROZEN or CLOSED",
  },
  default: "ACTIVE"
 },
 currency: {
  type: String,
  required: [true, "Currency is required for creating an account"],
  default: "INR"
 },

}, {
 timestamps: true
})

// indexes created on user and status fields - COMPOUND INDEX
accountSchema.index({ user: 1, status: 1 }) // user: 1 is used to create an index on user field in ascending order. status:1 is used for status field
const accountModel = mongoose.model("account", accountSchema);

export default accountModel;